// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbwiTUaTpAJpbXeTNP6uW_Gy9FWxo3piY',
    appId: '1:910538792854:web:2a2593bf51e6bd4e1d47b7',
    messagingSenderId: '910538792854',
    projectId: 'spotifyronclone01',
    authDomain: 'spotifyronclone01.firebaseapp.com',
    storageBucket: 'spotifyronclone01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwkSDJJ8vaAXOE3E54C93Gq2THvzt7vmM',
    appId: '1:910538792854:android:0fa6a769e9d95a531d47b7',
    messagingSenderId: '910538792854',
    projectId: 'spotifyronclone01',
    storageBucket: 'spotifyronclone01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwnkIkLFSG-zprPi3A5u_3Uxc9mz0tQC0',
    appId: '1:910538792854:ios:510f763efd0b7f621d47b7',
    messagingSenderId: '910538792854',
    projectId: 'spotifyronclone01',
    storageBucket: 'spotifyronclone01.firebasestorage.app',
    iosBundleId: 'com.example.ronfltapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwnkIkLFSG-zprPi3A5u_3Uxc9mz0tQC0',
    appId: '1:910538792854:ios:510f763efd0b7f621d47b7',
    messagingSenderId: '910538792854',
    projectId: 'spotifyronclone01',
    storageBucket: 'spotifyronclone01.firebasestorage.app',
    iosBundleId: 'com.example.ronfltapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbwiTUaTpAJpbXeTNP6uW_Gy9FWxo3piY',
    appId: '1:910538792854:web:2a13420af192ff781d47b7',
    messagingSenderId: '910538792854',
    projectId: 'spotifyronclone01',
    authDomain: 'spotifyronclone01.firebaseapp.com',
    storageBucket: 'spotifyronclone01.firebasestorage.app',
  );
}
